default_image := "mcr.microsoft.com/devcontainers/base:ubuntu"

# Default: list available recipes
default:
    @just --list

# ─── Setup ────────────────────────────────────────────────────────────────────

# Install devcontainer CLI (run once)
setup:
    npm install -g @devcontainers/cli

# ─── Testing ──────────────────────────────────────────────────────────────────

# Run all tests for a feature (autogenerated + scenarios + duplicate)
test feature image=default_image:
    devcontainer features test --project-folder . -f {{feature}} -i {{image}}

# Run autogenerated tests for a feature against a single image
test-image feature image=default_image:
    devcontainer features test --project-folder . --skip-scenarios --skip-duplicated -f {{feature}} -i {{image}}

# Run autogenerated tests for a feature against every image in compatibility.txt
test-compat feature:
    #!/usr/bin/env bash
    set -euo pipefail
    compat="test/{{feature}}/compatibility.txt"
    if [ ! -f "$compat" ]; then
        echo "ERROR: test/{{feature}}/compatibility.txt not found" >&2
        exit 1
    fi
    while IFS= read -r image || [ -n "$image" ]; do
        [[ -z "$image" || "$image" =~ ^[[:space:]]*# ]] && continue
        echo "==> {{feature}} on ${image}"
        devcontainer features test --project-folder . --skip-scenarios --skip-duplicated -f {{feature}} -i "$image" < /dev/null
    done < "$compat"

# Run duplicate tests for a feature against a single image
test-duplicate feature image=default_image:
    devcontainer features test --project-folder . --skip-scenarios --skip-autogenerated -f {{feature}} -i {{image}}

# Run duplicate tests for a feature against every image in compatibility.txt
test-duplicate-compat feature:
    #!/usr/bin/env bash
    set -euo pipefail
    compat="test/{{feature}}/compatibility.txt"
    if [ ! -f "$compat" ]; then
        echo "ERROR: test/{{feature}}/compatibility.txt not found" >&2
        exit 1
    fi
    while IFS= read -r image || [ -n "$image" ]; do
        [[ -z "$image" || "$image" =~ ^[[:space:]]*# ]] && continue
        echo "==> {{feature}} duplicate on ${image}"
        devcontainer features test --project-folder . --skip-scenarios --skip-autogenerated -f {{feature}} -i "$image" < /dev/null
    done < "$compat"

# Run scenario tests only for a feature
test-scenarios feature:
    devcontainer features test --project-folder . -f {{feature}} --skip-autogenerated --skip-duplicated

# Run global integration tests (_global/ suite)
test-global:
    devcontainer features test --project-folder . --global-scenarios-only

# ─── Linting ──────────────────────────────────────────────────────────────────

# Lint a single feature's install.sh with shellcheck
lint feature:
    shellcheck -S error src/{{feature}}/install.sh

# Lint all features' install.sh files
lint-all:
    #!/usr/bin/env bash
    set -euo pipefail
    exit_code=0
    for f in src/*/install.sh; do
        [ -f "$f" ] || continue
        echo "==> $f"
        shellcheck -S error "$f" || exit_code=1
    done
    exit "$exit_code"

# ─── Validation ───────────────────────────────────────────────────────────────

# Validate all devcontainer-feature.json files (JSON syntax check)
validate:
    #!/usr/bin/env bash
    set -euo pipefail
    exit_code=0
    for f in src/*/devcontainer-feature.json; do
        [ -f "$f" ] || continue
        if jq empty "$f" 2>/dev/null; then
            echo "ok: $f"
        else
            echo "INVALID JSON: $f" >&2
            exit_code=1
        fi
    done
    exit "$exit_code"
